import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useContext } from 'react'
import { AboutWrapper } from '../components/about'
import { CarouselContent, CarouselWrapper } from '../components/carousel'
import { ScrollContainer } from '../components/lib/useScroll'
import { MainVisual } from '../components/mainvisual'
import { Nav } from '../components/nav'
import { Title } from '../components/title'
import { Work } from '../components/work'

const Home: NextPage = () => {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <MainVisual/>
      <AboutWrapper/>
      <Work/>
    </div>
  )
}

export default Home
