import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useContext } from 'react'
import { AboutWrapper } from '../components/about'
import { CarouselContent, CarouselWrapper } from '../components/carousel'
import { ScrollContainer } from '../components/lib/useScroll'
import { MainVisual } from '../components/mainvisual'
import { Nav } from '../components/nav'

const Home: NextPage = () => {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
      <Nav/>
      <h1 className='text-lg p-3'>Future株式会社</h1>
      </header>
      <MainVisual/>
      {/* <div className='w-screen h-screen'>
      <CarouselWrapper>
        <CarouselContent description='test' src="/assets/disp.jpg"/>
        <CarouselContent description='test' src="/assets/img4.jpg"/>
        <CarouselContent description='test' src="/assets/elijah-hiett-f0huI7_HjWw-unsplash (1).jpeg"/>
      </CarouselWrapper>
      </div> */}
      <AboutWrapper/>
    </div>
  )
}

export default Home
